export const mockCompanies = [
  {
    id: 'comp_1',
    name: 'BioNova Therapeutics',
    sector: 'Biotech',
    subsector: 'Oncology',
    stage: 'Series C',
    geography: 'Boston, MA',
    website: 'https://bionova.example.com',
    modality: 'Small Molecule',
    lifecycleStage: 'Clinical Stage',
    summary: 'BioNova is developing next-generation targeted therapies for solid tumors with a focus on KRAS-driven cancers. They recently completed enrollment in their Phase 2 trial.',
    employeeCount: 180,
    fundingTotal: 145000000,
    lastFundingDate: new Date('2025-11-15'),
    leadInvestorId: 'inv_2',
    activeHires: [
      { title: 'VP Clinical Development', department: 'Clinical', seniority: 'VP', postedDate: '2026-02-10' },
      { title: 'Director of Regulatory Affairs', department: 'Regulatory', seniority: 'Director', postedDate: '2026-02-15' },
      { title: 'Senior Clinical Research Manager', department: 'Clinical', seniority: 'Senior Manager', postedDate: '2026-02-20' },
    ],
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'comp_2',
    name: 'DiagnostiX Labs',
    sector: 'Diagnostics',
    subsector: 'Liquid Biopsy',
    stage: 'Series B',
    geography: 'San Francisco, CA',
    website: 'https://diagnostix.example.com',
    modality: 'Molecular Diagnostics',
    lifecycleStage: 'Commercial Stage',
    summary: 'DiagnostiX is commercializing a liquid biopsy platform for early cancer detection. Their FDA-cleared test is now being adopted by major health systems.',
    employeeCount: 95,
    fundingTotal: 78000000,
    lastFundingDate: new Date('2025-09-20'),
    leadInvestorId: 'inv_1',
    activeHires: [
      { title: 'Chief Commercial Officer', department: 'Commercial', seniority: 'C-Suite', postedDate: '2026-02-18' },
      { title: 'VP Sales', department: 'Commercial', seniority: 'VP', postedDate: '2026-02-18' },
      { title: 'Director Market Access', department: 'Market Access', seniority: 'Director', postedDate: '2026-02-22' },
      { title: 'Regional Sales Manager – West', department: 'Commercial', seniority: 'Manager', postedDate: '2026-02-25' },
    ],
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'comp_3',
    name: 'ClinPath Solutions',
    sector: 'CRO/CDMO',
    subsector: 'Clinical Research',
    stage: 'Growth',
    geography: 'Raleigh, NC',
    website: 'https://clinpath.example.com',
    modality: 'Services',
    lifecycleStage: 'Commercial Stage',
    summary: 'ClinPath is a specialized CRO focused on oncology and rare disease trials. They recently expanded into Phase 3 capabilities and won three major pharma contracts.',
    employeeCount: 450,
    fundingTotal: 220000000,
    lastFundingDate: new Date('2025-07-10'),
    leadInvestorId: null,
    activeHires: [
      { title: 'CFO', department: 'Finance', seniority: 'C-Suite', postedDate: '2026-01-28' },
      { title: 'Chief Business Officer', department: 'Business Development', seniority: 'C-Suite', postedDate: '2026-01-28' },
      { title: 'VP Clinical Operations', department: 'Clinical', seniority: 'VP', postedDate: '2026-02-05' },
    ],
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'comp_4',
    name: 'GenVec Bio',
    sector: 'Biotech',
    subsector: 'Gene Therapy',
    stage: 'Series A',
    geography: 'San Diego, CA',
    website: 'https://genvec.example.com',
    modality: 'Gene Therapy',
    lifecycleStage: 'Preclinical',
    summary: 'GenVec Bio is developing AAV-based gene therapies for rare pediatric neurological disorders. Their lead program entered IND-enabling studies.',
    employeeCount: 45,
    fundingTotal: 35000000,
    lastFundingDate: new Date('2026-01-05'),
    leadInvestorId: 'inv_1',
    activeHires: [
      { title: 'Head of Manufacturing', department: 'Manufacturing', seniority: 'Head', postedDate: '2026-02-01' },
      { title: 'QA Director', department: 'Quality', seniority: 'Director', postedDate: '2026-02-01' },
      { title: 'Regulatory Affairs Director', department: 'Regulatory', seniority: 'Director', postedDate: '2026-02-08' },
    ],
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'comp_5',
    name: 'MedTech Innovations',
    sector: 'MedTech',
    subsector: 'Surgical Robotics',
    stage: 'Pre-IPO',
    geography: 'Chicago, IL',
    website: 'https://medtech-innov.example.com',
    modality: 'Medical Device',
    lifecycleStage: 'Commercial Stage',
    summary: 'MedTech Innovations has developed a next-gen robotic surgery platform for minimally invasive procedures. They are preparing for a Nasdaq IPO.',
    employeeCount: 620,
    fundingTotal: 380000000,
    lastFundingDate: new Date('2025-06-30'),
    leadInvestorId: 'inv_2',
    activeHires: [
      { title: 'VP EMEA', department: 'Commercial', seniority: 'VP', postedDate: '2026-01-20' },
      { title: 'Country GM Germany', department: 'Commercial', seniority: 'GM', postedDate: '2026-01-20' },
      { title: 'VP Finance', department: 'Finance', seniority: 'VP', postedDate: '2026-02-10' },
      { title: 'Medical Director EMEA', department: 'Medical Affairs', seniority: 'Director', postedDate: '2026-02-12' },
    ],
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date(),
  },
]

export const mockInvestors = [
  {
    id: 'inv_1',
    name: 'HealthVentures Capital',
    geography: 'Boston, MA',
    stageFocus: ['Series A', 'Series B'],
    sectorFocus: ['Biotech', 'MedTech', 'Diagnostics'],
    website: 'https://healthventures.example.com',
    activitySummary: 'Top-tier life sciences VC with $2B AUM, backing disruptive healthcare companies across the US and Europe. Recently closed Fund V at $800M.',
    aum: 2000000000,
    recentFundSize: 800000000,
    capitalDeployed: 1200000000,
    averageDealSize: 45000000,
    totalInvestments: 28,
    engagementScore: 94,
    portfolioCompanyIds: ['comp_2', 'comp_4'],
    typicalCoInvestors: [
      { name: 'Atlas Ventures', deals: 9, focus: 'Biotech' },
      { name: 'Flagship Pioneering', deals: 7, focus: 'Biotech' },
      { name: 'Orbis BioFund', deals: 5, focus: 'Cell Therapy' },
      { name: 'ARCH Venture Partners', deals: 4, focus: 'Gene Therapy' },
      { name: 'NEA', deals: 3, focus: 'MedTech' },
    ],
    expectedPortfolioHiring: [
      { companyName: 'DiagnostiX Labs', roles: ['Chief Commercial Officer', 'VP Sales', 'Director Market Access'], reason: '15+ job posts detected post-FDA Breakthrough Designation', urgency: 'High' },
      { companyName: 'GenVec Bio', roles: ['Head of Manufacturing', 'QA Director', 'Regulatory Affairs Director'], reason: 'Series A + IND-enabling studies initiated', urgency: 'Medium' },
    ],
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'inv_2',
    name: 'Orbis BioFund',
    geography: 'San Francisco, CA',
    stageFocus: ['Series B', 'Series C', 'Growth'],
    sectorFocus: ['Biotech', 'Genomics', 'Cell Therapy'],
    website: 'https://orbis-bio.example.com',
    activitySummary: 'Specialist biotech fund focused on clinical-stage companies. Known for providing strategic operating support post-investment.',
    aum: 1200000000,
    recentFundSize: 450000000,
    capitalDeployed: 780000000,
    averageDealSize: 72000000,
    totalInvestments: 14,
    engagementScore: 87,
    portfolioCompanyIds: ['comp_1', 'comp_5'],
    typicalCoInvestors: [
      { name: 'HealthVentures Capital', deals: 5, focus: 'Biotech' },
      { name: 'Third Rock Ventures', deals: 6, focus: 'Oncology' },
      { name: 'GV (Google Ventures)', deals: 4, focus: 'Genomics' },
      { name: 'Foresite Capital', deals: 4, focus: 'Biotech' },
      { name: 'RA Capital Management', deals: 3, focus: 'Clinical Stage' },
    ],
    expectedPortfolioHiring: [
      { companyName: 'BioNova Therapeutics', roles: ['Chief Scientific Officer', 'VP Clinical Development', 'VP Regulatory Affairs'], reason: 'Series C + positive Phase 2 data for KRAS inhibitor', urgency: 'High' },
      { companyName: 'NovaSynth Bio', roles: ['CFO', 'Chief Business Officer', 'VP Clinical Operations'], reason: 'New CEO appointment + $250M pharma partnership', urgency: 'High' },
    ],
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date(),
  },
]

export const mockSignals = [
  {
    id: 'sig_1',
    signalType: 'funding',
    title: 'BioNova Therapeutics Closes $85M Series C Round',
    summary: 'BioNova Therapeutics announced the closing of an $85 million Series C financing led by Orbis BioFund, with participation from existing investors HealthVentures Capital and Atlas Ventures.',
    whyItMatters: 'Series C funding of this size typically signals an 18-24 month runway to key clinical milestones and a significant hiring push across clinical, regulatory, and commercial functions.',
    companyId: 'comp_1',
    investorId: 'inv_2',
    sourceUrl: 'https://bionova.example.com/press',
    sourceName: 'BioSpace',
    publishedAt: new Date('2025-11-15'),
    relevanceScore: 92,
    impactedFunctions: ['Clinical Operations', 'Regulatory Affairs', 'Business Development'],
    tags: ['Series C', 'Oncology', 'KRAS'],
    bdAngle: 'Post-funding hiring surge expected. Target VP Clinical Operations and Chief Medical Officer for executive search. Drug development milestones will drive need for CRO partnerships.',
    geography: 'Boston, MA',
    sector: 'Biotech',
    createdAt: new Date('2025-11-15'),
  },
  {
    id: 'sig_2',
    signalType: 'hiring',
    title: 'DiagnostiX Labs Posts 15+ Senior Positions Including Chief Commercial Officer',
    summary: 'DiagnostiX Labs has posted over 15 new positions on LinkedIn, including a Chief Commercial Officer, VP of Sales, and Director of Market Access, signaling an aggressive commercial scale-up.',
    whyItMatters: 'The hiring of a CCO and commercial leadership team signals transition from product development to market capture. This is a prime window for executive search engagements.',
    companyId: 'comp_2',
    investorId: null,
    sourceUrl: 'https://linkedin.com/jobs',
    sourceName: 'LinkedIn',
    publishedAt: new Date('2026-02-20'),
    relevanceScore: 88,
    impactedFunctions: ['Commercial', 'Sales', 'Market Access'],
    tags: ['Hiring Surge', 'Commercial Build-out', 'Diagnostics'],
    bdAngle: 'Ideal moment to pitch retained executive search for CCO role. Company will also need VP Sales, Regional Sales Managers, and KAMs. High-velocity placement opportunity.',
    geography: 'San Francisco, CA',
    sector: 'Diagnostics',
    createdAt: new Date('2026-02-20'),
  },
  {
    id: 'sig_3',
    signalType: 'leadership',
    title: 'ClinPath Solutions Appoints New CEO from Covance',
    summary: 'ClinPath Solutions announced the appointment of Dr. Sarah Chen as CEO, joining from Covance where she led their oncology service line. The previous CEO transitions to Executive Chairman.',
    whyItMatters: 'New CEO appointments, especially from larger CROs, signal organizational transformation. New leaders typically rebuild their executive teams within 90-180 days of joining.',
    companyId: 'comp_3',
    investorId: null,
    sourceUrl: 'https://clinpath.example.com/news',
    sourceName: 'ClinicalTrials.gov News',
    publishedAt: new Date('2026-01-10'),
    relevanceScore: 85,
    impactedFunctions: ['Executive Leadership', 'Business Development', 'Clinical Operations'],
    tags: ['CEO Appointment', 'Leadership Change', 'CRO'],
    bdAngle: 'Engage Dr. Chen in first 30 days. New CEOs building teams are receptive to executive search partnerships. Focus pitch on rebuilding the C-suite and VP layer.',
    geography: 'Raleigh, NC',
    sector: 'CRO/CDMO',
    createdAt: new Date('2026-01-10'),
  },
  {
    id: 'sig_4',
    signalType: 'funding',
    title: 'GenVec Bio Secures $35M Series A to Advance Gene Therapy Pipeline',
    summary: 'GenVec Bio has raised $35 million in Series A financing led by HealthVentures Capital. The funds will be used to advance their lead AAV-based program into IND-enabling studies.',
    whyItMatters: 'Series A funding for a gene therapy company entering IND studies means 12-18 months of hiring across scientific, clinical, and regulatory functions.',
    companyId: 'comp_4',
    investorId: 'inv_1',
    sourceUrl: 'https://genvec.example.com/investors',
    sourceName: 'Fierce Biotech',
    publishedAt: new Date('2026-01-05'),
    relevanceScore: 79,
    impactedFunctions: ['Research', 'Regulatory Affairs', 'Clinical Development'],
    tags: ['Series A', 'Gene Therapy', 'AAV', 'Rare Disease'],
    bdAngle: 'Early-stage but highly active. Target VP Research and VP Regulatory Affairs placements. Build relationship now to become preferred partner as they scale.',
    geography: 'San Diego, CA',
    sector: 'Biotech',
    createdAt: new Date('2026-01-05'),
  },
  {
    id: 'sig_5',
    signalType: 'expansion',
    title: 'MedTech Innovations Opens European Headquarters in Germany',
    summary: 'MedTech Innovations announced the opening of its European headquarters in Munich, Germany, with plans to hire 100+ employees across clinical, commercial, and operational roles.',
    whyItMatters: 'European expansion from a pre-IPO company requires building an entirely new leadership and operational team. High-volume executive and management hiring expected.',
    companyId: 'comp_5',
    investorId: null,
    sourceUrl: 'https://medtech-innov.example.com/press',
    sourceName: 'MedCity News',
    publishedAt: new Date('2026-02-01'),
    relevanceScore: 91,
    impactedFunctions: ['Commercial', 'Clinical Operations', 'Regulatory Affairs', 'Finance'],
    tags: ['European Expansion', 'Pre-IPO', 'MedTech', 'International'],
    bdAngle: 'European expansion playbook. Pitch retained search for VP EMEA, Country Managers, Medical Directors. Multi-placement mandate opportunity with 6-12 month pipeline.',
    geography: 'Munich, Germany',
    sector: 'MedTech',
    createdAt: new Date('2026-02-01'),
  },
  {
    id: 'sig_6',
    signalType: 'clinical',
    title: 'BioNova Reports Positive Phase 2 Data for KRAS Inhibitor BNV-401',
    summary: 'BioNova Therapeutics announced positive topline data from its Phase 2 study of BNV-401 in KRAS G12C mutant non-small cell lung cancer, showing 42% overall response rate vs 18% for standard of care.',
    whyItMatters: 'Positive Phase 2 data is a key catalyst for Phase 3 investment and partnering activity. Expect significant expansion of clinical ops, biostatistics, and regulatory teams.',
    companyId: 'comp_1',
    investorId: null,
    sourceUrl: 'https://bionova.example.com/data',
    sourceName: 'ASCO Press Release',
    publishedAt: new Date('2026-03-01'),
    relevanceScore: 94,
    impactedFunctions: ['Clinical Operations', 'Biostatistics', 'Medical Affairs', 'Regulatory'],
    tags: ['Phase 2', 'Positive Data', 'NSCLC', 'KRAS'],
    bdAngle: 'Phase 3 transition creates massive hiring need. 50-100 clinical staff needed. Target CSO, CMO, and VP Biostatistics as priority placements before Phase 3 initiation.',
    geography: 'Boston, MA',
    sector: 'Biotech',
    createdAt: new Date('2026-03-01'),
  },
  {
    id: 'sig_7',
    signalType: 'partnership',
    title: 'ClinPath Solutions Signs $250M Strategic Partnership with Major Pharma',
    summary: 'ClinPath Solutions announced a strategic partnership with a top-10 pharmaceutical company valued at $250M over 5 years, covering oncology Phase 2/3 trials globally.',
    whyItMatters: 'A $250M pharma partnership requires ClinPath to significantly scale its operations. Expect 200+ new hires across clinical, data management, and project management.',
    companyId: 'comp_3',
    investorId: null,
    sourceUrl: 'https://clinpath.example.com/partnerships',
    sourceName: 'Drug Discovery News',
    publishedAt: new Date('2026-02-15'),
    relevanceScore: 87,
    impactedFunctions: ['Clinical Operations', 'Data Management', 'Project Management'],
    tags: ['Strategic Partnership', 'CRO', 'Pharma', 'Scale-Up'],
    bdAngle: 'Major growth mandate. ClinPath needs to hire at scale. Position as talent partner for operational scale-up. Focus on project managers, clinical monitors, and data managers.',
    geography: 'Raleigh, NC',
    sector: 'CRO/CDMO',
    createdAt: new Date('2026-02-15'),
  },
  {
    id: 'sig_8',
    signalType: 'regulatory',
    title: 'DiagnostiX Labs Receives FDA Breakthrough Device Designation',
    summary: 'DiagnostiX Labs announced receipt of FDA Breakthrough Device Designation for its multi-cancer early detection liquid biopsy test, accelerating its path to FDA clearance.',
    whyItMatters: 'Breakthrough Device Designation accelerates FDA review and strengthens commercial positioning. This typically triggers pre-commercialization hiring 12-18 months ahead.',
    companyId: 'comp_2',
    investorId: null,
    sourceUrl: 'https://diagnostix.example.com/regulatory',
    sourceName: 'FDA News Feed',
    publishedAt: new Date('2026-03-05'),
    relevanceScore: 83,
    impactedFunctions: ['Regulatory Affairs', 'Medical Affairs', 'Commercial'],
    tags: ['FDA Breakthrough', 'Diagnostics', 'Liquid Biopsy', 'Regulatory'],
    bdAngle: 'Strong signal for hiring in regulatory and commercial. Target VP Regulatory Affairs and Director Medical Affairs. Company will also need health economics expertise.',
    geography: 'San Francisco, CA',
    sector: 'Diagnostics',
    createdAt: new Date('2026-03-05'),
  },
  {
    id: 'sig_9',
    signalType: 'hiring',
    title: 'GenVec Bio Hiring Head of Manufacturing and Process Development',
    summary: 'GenVec Bio has posted a Head of Manufacturing and Process Development role, indicating transition from research-stage to production capabilities for their AAV programs.',
    whyItMatters: 'Hiring manufacturing leadership is a key indicator of clinical readiness. This role appointment signals GenVec is scaling toward IND filing within 6-12 months.',
    companyId: 'comp_4',
    investorId: null,
    sourceUrl: 'https://linkedin.com/jobs',
    sourceName: 'LinkedIn',
    publishedAt: new Date('2026-02-28'),
    relevanceScore: 76,
    impactedFunctions: ['Manufacturing', 'Process Development', 'Quality'],
    tags: ['Manufacturing Build', 'Gene Therapy', 'CMC', 'IND-Enabling'],
    bdAngle: 'Perfect timing to engage with search for Head of Manufacturing. Also flag upcoming needs for QA Director, Analytical Development Director.',
    geography: 'San Diego, CA',
    sector: 'Biotech',
    createdAt: new Date('2026-02-28'),
  },
  {
    id: 'sig_10',
    signalType: 'funding',
    title: 'HealthVentures Capital Raises $800M Fund V Focused on Clinical-Stage Assets',
    summary: 'HealthVentures Capital announced the close of its fifth fund at $800M, focused on clinical-stage life sciences companies. The fund will make 15-20 new investments over 3 years.',
    whyItMatters: 'New fund close means HealthVentures will be actively deploying capital in biotech and medtech. All portfolio companies from Fund V will need executive talent as they build out.',
    companyId: null,
    investorId: 'inv_1',
    sourceUrl: 'https://healthventures.example.com/news',
    sourceName: 'PE Hub',
    publishedAt: new Date('2026-03-08'),
    relevanceScore: 80,
    impactedFunctions: ['Executive Leadership', 'Business Development', 'Finance'],
    tags: ['Fund Close', 'VC', 'Life Sciences Investment', 'New Fund'],
    bdAngle: 'Approach HealthVentures as a strategic talent partner for their portfolio companies. Offer preferred recruiter status across all Fund V investments.',
    geography: 'Boston, MA',
    sector: 'Biotech',
    createdAt: new Date('2026-03-08'),
  },
]

export const mockOpportunities = [
  {
    id: 'opp_1',
    companyId: 'comp_1',
    linkedSignals: ['sig_1', 'sig_6'],
    opportunityScore: 94,
    momentumScore: 92,
    timingWindow: 'Act Now (30 days)',
    recommendedStakeholder: 'Chief Scientific Officer',
    likelyHiringNeed: 'VP Clinical Operations, VP Regulatory Affairs, Chief Medical Officer, 3-4 Director-level clinical hires ahead of Phase 3 initiation',
    outreachAngle: 'Congratulate on Phase 2 data and position your firm as the go-to partner for their Phase 3 team build. Reference your track record in oncology C-suite placements.',
    lifecycleContext: 'BioNova is at a critical inflection point following positive Phase 2 data. With fresh Series C funding and Phase 3 on the horizon, they will need to 3x their clinical and regulatory headcount within 18 months.',
    isArchived: false,
    createdAt: new Date('2026-03-05'),
    updatedAt: new Date(),
  },
  {
    id: 'opp_2',
    companyId: 'comp_2',
    linkedSignals: ['sig_2', 'sig_8'],
    opportunityScore: 89,
    momentumScore: 86,
    timingWindow: 'Act Now (30 days)',
    recommendedStakeholder: 'CEO / Co-founder',
    likelyHiringNeed: 'Chief Commercial Officer, VP Sales, Director Market Access, Regional Sales Managers (x5), KAMs (x10+)',
    outreachAngle: 'Position as commercial talent specialists who have built CCO-to-field-force teams for diagnostics companies. The FDA Breakthrough Designation creates urgency.',
    lifecycleContext: 'DiagnostiX is transitioning from R&D to commercial. With FDA Breakthrough Designation and active CCO search, they are in full commercial build-out mode. Multiple simultaneous placements possible.',
    isArchived: false,
    createdAt: new Date('2026-03-06'),
    updatedAt: new Date(),
  },
  {
    id: 'opp_3',
    companyId: 'comp_3',
    linkedSignals: ['sig_3', 'sig_7'],
    opportunityScore: 87,
    momentumScore: 84,
    timingWindow: 'Next 60 Days',
    recommendedStakeholder: 'CEO (Dr. Sarah Chen)',
    likelyHiringNeed: 'New C-suite as new CEO rebuilds team: CFO, Chief Business Officer, Chief People Officer, and 2-3 VP-level hires in clinical and operational areas',
    outreachAngle: 'Engage new CEO directly. Reference her Covance background and the opportunity to build her dream team. The pharma partnership contract creates urgency for scaling.',
    lifecycleContext: 'New CEO + major pharma partnership creates a dual hiring catalyst. Dr. Chen will want to bring in trusted colleagues and also scale rapidly to fulfill the $250M partnership obligations.',
    isArchived: false,
    createdAt: new Date('2026-02-20'),
    updatedAt: new Date(),
  },
  {
    id: 'opp_4',
    companyId: 'comp_5',
    linkedSignals: ['sig_5'],
    opportunityScore: 91,
    momentumScore: 88,
    timingWindow: 'Act Now (30 days)',
    recommendedStakeholder: 'Chief Operating Officer',
    likelyHiringNeed: 'VP EMEA, Country GM for Germany, France, UK, Medical Director EMEA, Regulatory Director EMEA, Commercial Director EMEA',
    outreachAngle: 'Pitch as European life sciences specialists. Emphasize experience building EMEA teams for US-based medtech companies pre-IPO.',
    lifecycleContext: 'Pre-IPO company opening European HQ represents a 6-12 month high-volume mandate. 100+ hires needed across leadership and operational roles.',
    isArchived: false,
    createdAt: new Date('2026-02-05'),
    updatedAt: new Date(),
  },
  {
    id: 'opp_5',
    companyId: 'comp_4',
    linkedSignals: ['sig_4', 'sig_9'],
    opportunityScore: 76,
    momentumScore: 74,
    timingWindow: 'Next 90 Days',
    recommendedStakeholder: 'Chief Executive Officer',
    likelyHiringNeed: 'Head of Manufacturing & Process Development, QA Director, Analytical Development Director, Regulatory Affairs Director',
    outreachAngle: 'Position as gene therapy talent specialists. Reference CMC and manufacturing expertise as GenVec prepares for IND filing.',
    lifecycleContext: 'GenVec Bio is transitioning from research to clinical with IND-enabling studies beginning. Manufacturing and CMC build-up creates near-term hiring needs.',
    isArchived: false,
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date(),
  },
]
