import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import bcrypt from 'bcryptjs'
import { prisma } from '@/lib/db'
import { authOptions } from '@/lib/auth'

// ── GET /api/invite?token= ─────────────────────────────────────────────────────
// Validates an invite token and returns invite metadata (no auth required)

export async function GET(req: NextRequest) {
  const token = req.nextUrl.searchParams.get('token')
  if (!token) {
    return NextResponse.json({ error: 'Token is required.' }, { status: 400 })
  }

  if (!prisma) {
    return NextResponse.json({ error: 'Database unavailable.' }, { status: 503 })
  }

  try {
    const invite = await prisma.orgInvite.findUnique({
      where: { token },
      include: { org: { select: { name: true } } },
    })

    if (!invite) {
      return NextResponse.json({ error: 'This invite link is invalid or has expired.' }, { status: 404 })
    }
    if (invite.accepted) {
      return NextResponse.json({ error: 'This invite has already been accepted.' }, { status: 410 })
    }
    if (new Date() > invite.expiresAt) {
      return NextResponse.json({ error: 'This invite link has expired. Please ask your admin to resend it.' }, { status: 410 })
    }

    return NextResponse.json({
      email: invite.email,
      orgName: invite.org.name,
      role: invite.role,
    })
  } catch (err) {
    console.error('[invite GET]', err)
    return NextResponse.json({ error: 'Failed to validate invite.' }, { status: 500 })
  }
}

// ── POST /api/invite ───────────────────────────────────────────────────────────
// Dual-purpose:
//   1. Body = { token, name, password }  → accept an invite (creates user + membership)
//   2. Body = { email, role }            → create an invite (requires org_admin session)

export async function POST(req: NextRequest) {
  const body = await req.json()

  // ── Accept flow ──────────────────────────────────────────────────────────────
  if (body.token) {
    const { token, name, password } = body as { token: string; name: string; password: string }

    if (!token || !password) {
      return NextResponse.json({ error: 'Token and password are required.' }, { status: 400 })
    }

    if (!prisma) {
      return NextResponse.json({ error: 'Database unavailable.' }, { status: 503 })
    }

    try {
      const invite = await prisma.orgInvite.findUnique({ where: { token } })
      if (!invite || invite.accepted || new Date() > invite.expiresAt) {
        return NextResponse.json({ error: 'Invalid or expired invite.' }, { status: 410 })
      }

      const existing = await prisma.user.findUnique({ where: { email: invite.email } })
      if (existing) {
        // User already exists — just add membership
        const mem = await prisma.orgMembership.findFirst({
          where: { userId: existing.id, orgId: invite.orgId },
        })
        if (!mem) {
          await prisma.orgMembership.create({
            data: { userId: existing.id, orgId: invite.orgId, role: invite.role },
          })
        }
      } else {
        // Create user + membership
        const hash = await bcrypt.hash(password, 12)
        const user = await prisma.user.create({
          data: {
            name: name || invite.email.split('@')[0],
            email: invite.email,
            password: hash,
            hasCompletedOnboarding: true,
          },
        })
        await prisma.orgMembership.create({
          data: { userId: user.id, orgId: invite.orgId, role: invite.role },
        })
      }

      await prisma.orgInvite.update({ where: { token }, data: { accepted: true } })

      return NextResponse.json({ ok: true })
    } catch (err) {
      console.error('[invite POST accept]', err)
      return NextResponse.json({ error: 'Failed to accept invite.' }, { status: 500 })
    }
  }

  // ── Create invite flow ───────────────────────────────────────────────────────
  const session = await getServerSession(authOptions)
  if (!session?.user) {
    return NextResponse.json({ error: 'Unauthorised.' }, { status: 401 })
  }
  if (session.user.orgRole !== 'org_admin' && !session.user.isSuperAdmin) {
    return NextResponse.json({ error: 'Forbidden. Only org admins can send invites.' }, { status: 403 })
  }

  const { email, role = 'member' } = body as { email: string; role?: string }
  if (!email) {
    return NextResponse.json({ error: 'Email is required.' }, { status: 400 })
  }

  if (!prisma) {
    return NextResponse.json({ error: 'Database unavailable.' }, { status: 503 })
  }

  try {
    const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) // 7 days

    // token is auto-generated by Prisma (@default(cuid()))
    const invite = await prisma.orgInvite.create({
      data: {
        orgId: session.user.orgId!,
        email,
        role,
        expiresAt,
        invitedBy: session.user.id,
      },
    })

    // In production, send an email here via Resend / SendGrid / SES
    // await sendInviteEmail({ to: email, token, orgName: session.user.orgName })

    const inviteUrl = `${process.env.NEXTAUTH_URL}/invite?token=${token}`
    return NextResponse.json({ ok: true, inviteUrl, expiresAt })
  } catch (err) {
    console.error('[invite POST create]', err)
    return NextResponse.json({ error: 'Failed to create invite.' }, { status: 500 })
  }
}
